#!/bin/bash

# Author: Waleed Alhammami
# Date Created: 25/01/2023
# Last Modified: 25/01/2023

# Description
# Prints "This is my first script" to the terminal

# Usage
# our_first_script

echo "This is my first script"
exit 0