# Name of our workflow
name: My Test Workflow

# Define the trigger event(s)
# The [] brackets are to define a list, not needed if it's just one item
on: [push]
# Another example could be : [push, pull_request]

# Jobs run in parallel by default, each runs steps in sequence
jobs:
  # Job to print something out
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, Github Actions!"
      